# Generated by Django 4.1.6 on 2023-02-27 09:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('announcement', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='favorite_by',
            field=models.ManyToManyField(blank=True, null=True, related_name='favorite_ann', to=settings.AUTH_USER_MODEL, verbose_name='Добавили в избранное'),
        ),
    ]
