export const types = {
    'motherboard': {
        'id': 'ID',
        'form_factor': 'Форм-фактор',
        'socket': 'Сокет',
        'chipset': 'Чипсет'
    },
    'processor': {
        'id': 'ID',
        'manufacturer': 'Производитель',
        'package': 'Упаковка',
        'generation': 'Поколение',
        'series': 'Серия',
        'socket': 'Сокет',
        'max_frequency': 'Частота(ГГц)',
        'min_frequency': 'Частота в разгоне(ГГц)',
        'kernels': 'Кол-во ядер',
        'streams': 'Кол-во потоков',
        'cache_l2': 'Кэш L2(МБ)',
        'cache_l3': 'Кэш L3(МБ)',
        'tech_process': 'Техпроцесс(нм)',
        'type_ram': 'Поддерж. ОЗУ',
        'max_ram_size': 'Макс. ОЗУ',
        'max_ram_frequency': 'Макс. частота ОЗУ(ГГц)',
        'ram_canals': 'Кол-во каналов ОЗУ',
        'TDP': 'TDP',

    },
    'videocard': {
        'id': 'ID',
        'manufacturer': 'Производитель',
        'GPU': 'Графический процессор',
        'frequency_video_chip': 'Частота видеочипа(ГГц)',
        'microarchitecture': 'Микроархитектура',
        'tech_process': 'Техпроцесс(нм)',
        'memory': 'Объём памяти',
        'memory_bus_width': 'Ширина шины памяти',
        'memory_bandwidth': 'Пропускная способность шины памяти',
        'TMU': 'Кол-во текстурных блоков',
        'ROP': 'Кол-во блоков растеризации',
        'form_factor': 'Форм-фактор',
        'video_connectors': 'Видеоразъемы',
        'ray_tracing': 'Поддержка трассировки лучей',
    },
    'ram': {
        'id': 'ID',
        'type': 'Тип памяти',
        'form_factor': 'Форм-фактор',
        'capacity': 'Объём(Гб)',
        'frequency': 'Частота(МГц)',
        'CL': 'CAS Latency',
        'tRCD': 'RAS to CAS Delay',
        'tRP': 'Row Precharge Delay',
        'tRAS': 'Activate to Precharge Delay',
    },
    'rom': {
      'id': 'ID',
      'interface': 'Интерфейс',
      'form_factor': 'Форм-фактор',
      'capacity':'Объём(Тб)',
      'buffer_capacity':'Объём буффера(Мб)',
      'write_read_speed':'Скорость чтения/записи(Мбайт/сек)',
      'spindle_speed':'Скорость вращения шпинделя(об/мин)',
      'noise_level':'Уровень шума(дБ)',
    },
    'ssd': {
        'id': 'ID',
        'capacity':'Ёмкость(Гб)',
        'interface':'Интерфейс',
        'read':'Скорость чтения',
        'write':'Скорость записи',
        'bits_per_cell':'Кол-во бит на ячейку',
        'structure':'Структура',
        'NVMe':'NVMe',
        'DRAM_buffer':'DRAM буфер',
        'm2_key':'Тип ключа',
        'TBW':'Максимальный ресурс',
    },
    'powerunit': {
        'id': 'ID',
        'power': 'Мощность(Ватт)',
        'standard': 'Стандарт',
        'PFC': 'Коррекция коэффициента мощности',
        'certificate_80_plus':'Сертификация 80 plus',
        'mb_conn': 'Разъём питания материнской платы',
        'pin4_cpu': 'Количество разъемов 4-pin CPU',
        'pin4_4_cpu': 'Кол-во разъемов 4+4 pin CPU',
        'pin6_2_pci': 'Количество разъемов 6+2-pin PCI-E',
        'pin15_sata': 'Количество разъемов 15-pin SATA',
        'fan_diameter': 'Диаметр вентилятора',
    },
    'cooler': {
        'id': 'ID',
        'type': 'Тип',
        'sockets': 'Сокеты',
        'material': 'Материал',
        'MPD': 'Максимальная рассеиваемая мощность',
        'count_fans': 'Кол-во вентиляторов',
        'rotational_speed': 'Скорость вращения',
    },
    'computer': {
        'id': 'ID',
        'mother_board': 'Материнская плата',
        'processor': 'Процессор',
        'video_card': 'Видеокарта',
        'RAM': 'ОЗУ',
        'ROM': 'ПЗУ',
        'SSD': 'SSD',
        'power_unit': 'Блок питания',
        'cooler_for_processor': 'Кулер процессора',
        'body': 'Корпус',
    },
};